--CONSULTA CANTIDAD TOTAL MATERIAL POR CLASIFICACION

SELECT 

M.IDMATERIAL AS CODIGO_MATERIAL,
M.NOMBRE AS NOMBRE_MATERIAL,
M.PESO_GR AS PESO_GRAMOS,
M.IDSUPLIDOR AS CODIGO_SUPLIDOR,
M.UM AS UNIDAD_DE_MEDIDA,
M.COSTO,

S.N_Suplidor AS NOMBRE_SUPLIDOR,
C.Clasificacion_Material AS CLASIFICACION_MATERIAL,

L.N_LOTE AS LOTE,
L.CANTIDAD AS CANTIDAD_TOTAL

FROM MATERIAL AS M LEFT JOIN LOTE AS L ON M.IDMaterial = L.IDMaterial INNER JOIN CLASIFICACION AS C ON M.IDclasificacion = C.IDClasificacion INNER JOIN	SUPLIDOR AS S ON M.IDSuplidor = S.IDSuplidor

--SOLO CAMBIAR NUMERO DE CLASIFICACION PARA REALIZAR CONSULTA

--ID/CLASIFICACION
--1	Construccion
--2	Electricidad
--3	Plomeria
--4	Cerrajeria
--5	Pintura
--6	Herramientas
--7	Farmaceutica
--8	Iluminacion
--9	Otros
--10	Maderas
--11	Cristaleria
--12	Plasticos
--13	Equipos de seguridad
--14	Cocina
--15	MECANICA
--17	JOYERIA
--18	AVIACION

WHERE C.IDClasificacion = 17

