--CONSULTA CANTIDAD TOTAL MATERIAL POR NUMERO DE SUPLIDOR

SELECT 

M.IDMATERIAL AS CODIGO_MATERIAL,
M.NOMBRE AS NOMBRE_MATERIAL,
M.PESO_GR AS PESO_GRAMOS,
M.IDSUPLIDOR AS CODIGO_SUPLIDOR,
M.UM AS UNIDAD_DE_MEDIDA,
M.COSTO,

S.N_Suplidor AS NOMBRE_SUPLIDOR,
C.Clasificacion_Material AS CLASIFICACION_MATERIAL,

L.N_LOTE AS LOTE,
L.CANTIDAD AS CANTIDAD_TOTAL

FROM MATERIAL AS M LEFT JOIN LOTE AS L ON M.IDMaterial = L.IDMaterial INNER JOIN CLASIFICACION AS C ON M.IDclasificacion = C.IDClasificacion INNER JOIN	SUPLIDOR AS S ON M.IDSuplidor = S.IDSuplidor


--SOLO CAMBIAR NUMERO DE SUPLIDOR PARA REALIZAR CONSULTA
--LOS NUMEROS ESTAN ENTRE 5020,5030 Y 3

WHERE S.IDSuplidor=3